function countryFlag(code) {
  const base = 0x1F1E6
  return String.fromCodePoint(
    base + code.charCodeAt(0) - 65,
    base + code.charCodeAt(1) - 65,
  )
}

// First match wins. More specific rules come before general ones.
const KEYWORD_RULES = [
  // Life events
  [['boda', 'wedding', 'matrimonio', 'casamiento'],                     '💍'],
  [['despedida de soltera', 'despedida de soltero', 'bachelorette', 'bachelor party'], '🥂'],
  [['cumpleaños', 'birthday', 'cumple'],                                '🎂'],
  [['aniversario', 'anniversary'],                                      '🥂'],
  [['graduación', 'graduacion', 'graduation'],                          '🎓'],
  // Holidays
  [['navidad', 'christmas', 'xmas', 'nochebuena'],                     '🎄'],
  [['halloween'],                                                        '🎃'],
  [['año nuevo', 'new year', 'nochevieja', 'réveillon', 'reveillon'],  '🎆'],
  // Gatherings
  [['festival', 'feria', 'carnaval', 'carnival'],                      '🎪'],
  [['fiesta', 'party'],                                                  '🎉'],
  [['retiro', 'retreat', 'team building'],                              '🏕️'],
  // Water / beach
  [['playa', 'beach', 'cala', 'chiringuito'],                          '🏖️'],
  [['isla', 'island', 'islas', 'islands', 'atolón'],                   '🏝️'],
  [['crucero', 'cruise'],                                               '🚢'],
  [['surf'],                                                            '🏄'],
  [['buceo', 'diving', 'snorkel'],                                      '🤿'],
  [['lago', 'lake'],                                                    '🏞️'],
  // Mountain / snow
  [['ski', 'esqui', 'esquí', 'nieve', 'snow', 'pistas de ski'],        '⛷️'],
  [['montaña', 'mountain', 'sierra', 'alps', 'alpes', 'pico', 'cumbre', 'volcán'], '🏔️'],
  [['senderismo', 'hiking', 'trekking', 'trail', 'ruta'],              '🥾'],
  [['camping', 'acampada'],                                             '⛺'],
  // Nature
  [['desierto', 'desert', 'sahara'],                                   '🏜️'],
  [['selva', 'jungle', 'amazon', 'amazonas'],                          '🌿'],
  [['safari'],                                                          '🦁'],
  // Transport
  [['road trip', 'roadtrip', 'ruta en coche', 'ruta en carro'],        '🚗'],
  [['vuelta al mundo', 'world tour', 'around the world'],              '✈️'],
  // Seasonal
  [['verano', 'summer'],                                               '☀️'],
  [['invierno', 'winter'],                                             '❄️'],
  [['primavera', 'spring'],                                            '🌸'],
  [['otoño', 'autumn', 'fall'],                                        '🍂'],
]

// City → ISO-3166-1 alpha-2 country code.
// Multi-word names are listed before single-word ones to prevent partial matches.
const CITY_RULES = [
  ['buenos aires',       'AR'],
  ['rio de janeiro',     'BR'],
  ['são paulo',          'BR'],
  ['sao paulo',          'BR'],
  ['nueva york',         'US'],
  ['new york',           'US'],
  ['los angeles',        'US'],
  ['las vegas',          'US'],
  ['san francisco',      'US'],
  ['new orleans',        'US'],
  ['ciudad de mexico',   'MX'],
  ['ciudad de méxico',   'MX'],
  ['san jose',           'CR'],
  ['abu dhabi',          'AE'],
  ['hong kong',          'HK'],
  ['kuala lumpur',       'MY'],
  ['chiang mai',         'TH'],
  ['ho chi minh',        'VN'],
  ['siem reap',          'KH'],
  ['nueva delhi',        'IN'],
  ['new delhi',          'IN'],
  ['cape town',          'ZA'],
  ['ciudad del cabo',    'ZA'],
  ['san petersburgo',    'RU'],
  ['corea del sur',      'KR'],
  ['reino unido',        'GB'],
  ['tel aviv',           'IL'],
  ['reykjavik',          'IS'],
  ['reikiavik',          'IS'],
  ['edimburgo',          'GB'],
  ['edinburgh',          'GB'],
  ['manchester',         'GB'],
  ['amsterdam',          'NL'],
  ['rotterdam',          'NL'],
  ['bruselas',           'BE'],
  ['brussels',           'BE'],
  ['frankfurt',          'DE'],
  ['hamburgo',           'DE'],
  ['hamburg',            'DE'],
  ['múnich',             'DE'],
  ['munich',             'DE'],
  ['berlín',             'DE'],
  ['berlin',             'DE'],
  ['viena',              'AT'],
  ['vienna',             'AT'],
  ['salzburgo',          'AT'],
  ['salzburg',           'AT'],
  ['zúrich',             'CH'],
  ['zurich',             'CH'],
  ['ginebra',            'CH'],
  ['geneva',             'CH'],
  ['varsovia',           'PL'],
  ['warsaw',             'PL'],
  ['cracovia',           'PL'],
  ['krakow',             'PL'],
  ['kraków',             'PL'],
  ['budapest',           'HU'],
  ['praga',              'CZ'],
  ['prague',             'CZ'],
  ['estocolmo',          'SE'],
  ['stockholm',          'SE'],
  ['copenhague',         'DK'],
  ['copenhagen',         'DK'],
  ['helsinki',           'FI'],
  ['tallinn',            'EE'],
  ['tallin',             'EE'],
  ['vilnius',            'LT'],
  ['bucarest',           'RO'],
  ['bucharest',          'RO'],
  ['belgrado',           'RS'],
  ['belgrade',           'RS'],
  ['atenas',             'GR'],
  ['athens',             'GR'],
  ['mykonos',            'GR'],
  ['santorini',          'GR'],
  ['corfú',              'GR'],
  ['corfu',              'GR'],
  ['rodas',              'GR'],
  ['rhodes',             'GR'],
  ['creta',              'GR'],
  ['crete',              'GR'],
  ['estambul',           'TR'],
  ['istanbul',           'TR'],
  ['ankara',             'TR'],
  ['moscú',              'RU'],
  ['moscow',             'RU'],
  ['dubrovnik',          'HR'],
  ['zagreb',             'HR'],
  ['lisboa',             'PT'],
  ['lisbon',             'PT'],
  ['oporto',             'PT'],
  ['porto',              'PT'],
  ['madrid',             'ES'],
  ['barcelona',          'ES'],
  ['valencia',           'ES'],
  ['sevilla',            'ES'],
  ['málaga',             'ES'],
  ['malaga',             'ES'],
  ['bilbao',             'ES'],
  ['granada',            'ES'],
  ['alicante',           'ES'],
  ['ibiza',              'ES'],
  ['tenerife',           'ES'],
  ['lanzarote',          'ES'],
  ['fuerteventura',      'ES'],
  ['menorca',            'ES'],
  ['mallorca',           'ES'],
  ['palma',              'ES'],
  ['donostia',           'ES'],
  ['zaragoza',           'ES'],
  ['córdoba',            'ES'],
  ['cordoba',            'ES'],
  ['toledo',             'ES'],
  ['canarias',           'ES'],
  ['galicia',            'ES'],
  ['asturias',           'ES'],
  ['extremadura',        'ES'],
  ['andalucía',          'ES'],
  ['cataluña',           'ES'],
  ['paris',              'FR'],
  ['parís',              'FR'],
  ['lyon',               'FR'],
  ['marsella',           'FR'],
  ['marseille',          'FR'],
  ['niza',               'FR'],
  ['burdeos',            'FR'],
  ['bordeaux',           'FR'],
  ['estrasburgo',        'FR'],
  ['strasbourg',         'FR'],
  ['roma',               'IT'],
  ['rome',               'IT'],
  ['milán',              'IT'],
  ['milan',              'IT'],
  ['venecia',            'IT'],
  ['venice',             'IT'],
  ['florencia',          'IT'],
  ['florence',           'IT'],
  ['nápoles',            'IT'],
  ['naples',             'IT'],
  ['toscana',            'IT'],
  ['tuscany',            'IT'],
  ['sicilia',            'IT'],
  ['sicily',             'IT'],
  ['cerdeña',            'IT'],
  ['sardinia',           'IT'],
  ['turín',              'IT'],
  ['turin',              'IT'],
  ['bolonia',            'IT'],
  ['bologna',            'IT'],
  ['lima',               'PE'],
  ['cusco',              'PE'],
  ['cuzco',              'PE'],
  ['machu picchu',       'PE'],
  ['santiago',           'CL'],
  ['valparaíso',         'CL'],
  ['valparaiso',         'CL'],
  ['medellín',           'CO'],
  ['medellin',           'CO'],
  ['cartagena',          'CO'],
  ['bogotá',             'CO'],
  ['bogota',             'CO'],
  ['la habana',          'CU'],
  ['habana',             'CU'],
  ['havana',             'CU'],
  ['cancún',             'MX'],
  ['cancun',             'MX'],
  ['guadalajara',        'MX'],
  ['monterrey',          'MX'],
  ['toronto',            'CA'],
  ['vancouver',          'CA'],
  ['montreal',           'CA'],
  ['marrakech',          'MA'],
  ['marrakesh',          'MA'],
  ['casablanca',         'MA'],
  ['tokio',              'JP'],
  ['tokyo',              'JP'],
  ['osaka',              'JP'],
  ['kioto',              'JP'],
  ['kyoto',              'JP'],
  ['hiroshima',          'JP'],
  ['bangkok',            'TH'],
  ['phuket',             'TH'],
  ['bali',               'ID'],
  ['ubud',               'ID'],
  ['lombok',             'ID'],
  ['singapur',           'SG'],
  ['singapore',          'SG'],
  ['hanoi',              'VN'],
  ['saigon',             'VN'],
  ['mumbai',             'IN'],
  ['bombay',             'IN'],
  ['delhi',              'IN'],
  ['goa',                'IN'],
  ['pekín',              'CN'],
  ['beijing',            'CN'],
  ['shanghái',           'CN'],
  ['shanghai',           'CN'],
  ['sydney',             'AU'],
  ['melbourne',          'AU'],
  ['auckland',           'NZ'],
  ['washington',         'US'],
  ['chicago',            'US'],
  ['miami',              'US'],
  ['boston',             'US'],
  ['seattle',            'US'],
  ['orlando',            'US'],
  ['atlanta',            'US'],
  ['nashville',          'US'],
  ['denver',             'US'],
  ['dubai',              'AE'],
  ['dubái',              'AE'],
  ['doha',               'QA'],
  ['cairo',              'EG'],
  ['luxor',              'EG'],
  ['nairobi',            'KE'],
  ['kiiv',               'UA'],
  ['kyiv',               'UA'],
  ['oslo',               'NO'],
  ['london',             'GB'],
  ['londres',            'GB'],
]

// Country name → ISO code
const COUNTRY_RULES = [
  ['estados unidos',    'US'],
  ['united states',     'US'],
  ['reino unido',       'GB'],
  ['united kingdom',    'GB'],
  ['países bajos',      'NL'],
  ['netherlands',       'NL'],
  ['corea del sur',     'KR'],
  ['south korea',       'KR'],
  ['nueva zelanda',     'NZ'],
  ['new zealand',       'NZ'],
  ['costa rica',        'CR'],
  ['república dominicana', 'DO'],
  ['dominican',         'DO'],
  ['sudáfrica',         'ZA'],
  ['south africa',      'ZA'],
  ['españa',            'ES'],
  ['spain',             'ES'],
  ['francia',           'FR'],
  ['france',            'FR'],
  ['italia',            'IT'],
  ['italy',             'IT'],
  ['portugal',          'PT'],
  ['alemania',          'DE'],
  ['germany',           'DE'],
  ['england',           'GB'],
  ['inglaterra',        'GB'],
  ['holanda',           'NL'],
  ['bélgica',           'BE'],
  ['belgica',           'BE'],
  ['belgium',           'BE'],
  ['suiza',             'CH'],
  ['switzerland',       'CH'],
  ['austria',           'AT'],
  ['grecia',            'GR'],
  ['greece',            'GR'],
  ['croacia',           'HR'],
  ['croatia',           'HR'],
  ['turquía',           'TR'],
  ['turquia',           'TR'],
  ['turkey',            'TR'],
  ['noruega',           'NO'],
  ['norway',            'NO'],
  ['suecia',            'SE'],
  ['sweden',            'SE'],
  ['dinamarca',         'DK'],
  ['denmark',           'DK'],
  ['finlandia',         'FI'],
  ['finland',           'FI'],
  ['islandia',          'IS'],
  ['iceland',           'IS'],
  ['irlanda',           'IE'],
  ['ireland',           'IE'],
  ['polonia',           'PL'],
  ['poland',            'PL'],
  ['chequia',           'CZ'],
  ['czech',             'CZ'],
  ['hungría',           'HU'],
  ['hungary',           'HU'],
  ['rumania',           'RO'],
  ['romania',           'RO'],
  ['eslovaquia',        'SK'],
  ['slovakia',          'SK'],
  ['eslovenia',         'SI'],
  ['slovenia',          'SI'],
  ['serbia',            'RS'],
  ['bulgaria',          'BG'],
  ['estonia',           'EE'],
  ['letonia',           'LV'],
  ['lituania',          'LT'],
  ['ucrania',           'UA'],
  ['ukraine',           'UA'],
  ['rusia',             'RU'],
  ['russia',            'RU'],
  ['canadá',            'CA'],
  ['canada',            'CA'],
  ['mexico',            'MX'],
  ['méxico',            'MX'],
  ['cuba',              'CU'],
  ['jamaica',           'JM'],
  ['panamá',            'PA'],
  ['panama',            'PA'],
  ['colombia',          'CO'],
  ['venezuela',         'VE'],
  ['perú',              'PE'],
  ['peru',              'PE'],
  ['ecuador',           'EC'],
  ['bolivia',           'BO'],
  ['chile',             'CL'],
  ['argentina',         'AR'],
  ['uruguay',           'UY'],
  ['paraguay',          'PY'],
  ['brasil',            'BR'],
  ['brazil',            'BR'],
  ['marruecos',         'MA'],
  ['morocco',           'MA'],
  ['egipto',            'EG'],
  ['egypt',             'EG'],
  ['túnez',             'TN'],
  ['tunisia',           'TN'],
  ['kenia',             'KE'],
  ['kenya',             'KE'],
  ['emiratos',          'AE'],
  ['emirates',          'AE'],
  ['qatar',             'QA'],
  ['israel',            'IL'],
  ['india',             'IN'],
  ['china',             'CN'],
  ['japón',             'JP'],
  ['japan',             'JP'],
  ['tailandia',         'TH'],
  ['thailand',          'TH'],
  ['vietnam',           'VN'],
  ['indonesia',         'ID'],
  ['singapur',          'SG'],
  ['singapore',         'SG'],
  ['malasia',           'MY'],
  ['malaysia',          'MY'],
  ['filipinas',         'PH'],
  ['philippines',       'PH'],
  ['camboya',           'KH'],
  ['cambodia',          'KH'],
  ['maldivas',          'MV'],
  ['maldives',          'MV'],
  ['australia',         'AU'],
  ['usa',               'US'],
]

export function getTripEmoji(name) {
  if (!name) return null
  const lower = name.toLowerCase()

  for (const [keywords, emoji] of KEYWORD_RULES) {
    if (keywords.some((k) => lower.includes(k))) return emoji
  }

  for (const [city, code] of CITY_RULES) {
    if (lower.includes(city)) return countryFlag(code)
  }

  for (const [country, code] of COUNTRY_RULES) {
    if (lower.includes(country)) return countryFlag(code)
  }

  return null
}
